### ISSUE TITLE
Draggable placeholder ?

### ISSUE THREAD

**Issue by ManUtopiK** [ocavue/prosekit#295]
I'm experimenting some stuff with prosekit, essentially with Vue.js.
I want to say it works really well with Vue compared to Tiptap. Dynamic component (`<component :is="...`) doesn't play well in Tiptap. With prosekit, I don't see unexpected behavior inside a custom component with `defineVueNodeView`. 
Also, I like how you define the API. It's more like a composable API.
Thanks a lot for your work !

I added `draggable: true` with `defineNodeSpec` in a custom component. I can drag it, but we can't see a drop placeholder to see where the dragged element is dropped.
I wonder how to display it ? And I want to know if we can drag an element at the right or left of another element ?

**Comment by ocavue** [comment]
You can use the `defineDropCursor` function. Released in v0.2.7.


https://github.com/ocavue/prosekit/assets/24715727/a141dfcb-82d0-4499-8611-030aa1fee68f

**Comment by ManUtopiK** [comment]
I just saw that !
Your are so reactive. Thanks a lot!
