### ISSUE TITLE
Helpers and help

### ISSUE THREAD

**Issue by ManUtopiK** [ocavue/prosekit#313]
There are a bunch of [helpers function in tiptap](https://github.com/ueberdosis/tiptap/tree/731109b5667afdc6142de20a37c6f0b19ca6212f/packages/core/src/helpers).
Are there any plans to add those?
Maybe I can help ? I don't know what is it planed and the roadmap.

**Comment by ocavue** [comment]
Hey! First of all, thank you very much for your contribution recently. ProseKit is in an early stage and a lot of features need to be done. I just created a public roadmap [here](https://github.com/ocavue/prosekit/projects).

We will have a lot more helper functions during the development of ProseKit. In the meantime, if you want to contribute, you can submit pull requests to add the function you want under `packages/core/src/utils/` and export it in `packages/core/src/index.ts`.

**Comment by ManUtopiK** [comment]
Good to see a roadmap ! I've a lot of stuff to do those times, but I'll try to contribute at my best.
Thx !
