### ISSUE TITLE
Exposing unocss-shortcut ?

### ISSUE THREAD

**Issue by ManUtopiK** [ocavue/prosekit#394]
Sorry, one more demand :)
The more I explore and experiment, the more I realise that your work is really brilliant !

I want to know if you can expose the unocss-shortcut. We could import it and modify some keys as we want.

Maybe exporting this file as a [unocss preset](https://unocss.dev/config/presets) should be better for the future...

**Comment by ocavue** [comment]
Thanks for your kind words. After using https://ui.shadcn.com/ and other similar projects, 
now feel it might not be a good idea to publish the component style to NPM registry (via Unocss preset or just CSS files). Two reasons for that: 

1. For users, it's difficult to customize the styles. For example, you would first need to learn a bunch of CSS class names [in MUI](https://mui.com/material-ui/api/select/#classes) or a bunch of CSS variable names [in Remirror](https://github.com/remirror/remirror/blob/55602747f8d4134671de0b2d5488f8c5152342ea/packages/remirror__styles/theme.css#L202), and use the correct CSS selector priority to override them. 
2. For maintainers, it's difficult to update. Every CSS change could be potentially a breaking change, so style updating must be careful. 

I encourage users to copy and paste the component examples (as well as all the TailwindCSS/UnoCSS class names) to their projects, and customize/maintain these components themselves. You can toggle the "Code" switch to show the source code of components in the [examples page](https://prosekit.dev/examples).

I plan to make it easier to copy the styles by improving the following two things in the future:

1. Currently the origin class names (defined in `unocss-shortcut.js`) are shown when inspecting the website. I will fix that and only show TailwindCSS/UnoCSS class names.
![CleanShot 2024-02-21 at 17 42 07@2x](https://github.com/ocavue/prosekit/assets/24715727/326143fa-b828-4b81-958b-40f61cfe3b24)
2. I plan to add a CLI tool to install and/or update component source code to users' projects, like https://ui.shadcn.com/docs/cli

**Comment by ManUtopiK** [comment]
Ok. I understand your purpose, and really like your ideas. A CLI tool look like awesome!
