### ISSUE TITLE
PopoverContent placement

### ISSUE THREAD

**Issue by ManUtopiK** [ocavue/prosekit#452]
Hi!

I updated my components to use the new popover component. But I have an issue with the position.
I use Vue.js and define a vue component with `defineVueNodeView`. In this component, I want to make a simple dropdown menu.
So, the template is :
```html
<template>
  <PopoverRoot
    :open="open"
    :on-open-change="handleOpenChange"
  >
    <PopoverTrigger>
      <slot />
    </PopoverTrigger>

    <PopoverContent
      :placement="'bottom'"
      :offset="5"
    
      class="INLINE_MENU"
    >
      <slot name="menu" />
    </PopoverContent>
  </PopoverRoot>
</template>
```
The placement have no effect. I took a look on the [aria-ui doc](https://github.com/ocavue/aria-ui/tree/master/packages/popover) and tried other stuff like `data-side="bottom"` but without success.
What I missing ?

**Comment by ocavue** [comment]
Here is a demo using `<PopoverRoot>`, `<PopoverTrigger>` and `<PopoverContent>` in a Vue component (`<LanguageSelector>`), which will later be used in `defineVueNodeView()`. Hope this can help you.

Source code and live example: https://stackblitz.com/edit/github-nedpo3?file=src%2Flanguage-selector.vue

Screen recording: https://github.com/ocavue/prosekit/assets/24715727/746a6fa1-febd-43df-ad5f-056c0fdba0eb

**Comment by ManUtopiK** [comment]
Thanks for your demo. I've understand the issue, my reference element is too narrow, so the popup placement was incorrect.
I used different props and achieve what I want with :
```html
<PopoverContent
  placement="bottom"
  :offset="2"
  element-context="reference"
  :alt-boundary="true"
  strategy="fixed"
  class="INLINE_MENU_LINK"
>
```
