### ISSUE TITLE
Handle AutocompletePopover events

### ISSUE THREAD

**Issue by ManUtopiK** [ocavue/prosekit#470]
Does the `AutocompletePopover` callback [`onQueryChange` and `onOpenChange`](https://github.com/ocavue/prosekit/blob/master/packages/web/src/components/autocomplete/autocomplete-popover/props.ts) work as expected ?
No events are fired.
[reproduction](https://stackblitz.com/edit/github-nedpo3-oemqxs?file=src%2Fslash-menu.vue)

**Comment by ocavue** [comment]
![CleanShot 2024-05-03 at 05 01 22@2x](https://github.com/ocavue/prosekit/assets/24715727/eac50819-fcff-48db-af97-e463f8206007)

You made a mistake about `@on-query-change`. You would want to use `@query-change` or `:on-query-change`. 

Also, the latest version (0.6.8) has fixed some bugs about `onQueryChange` and `onOpenChange`. It's better to update the latest verison.

**Comment by ManUtopiK** [comment]
Arrf, it was so simple in fact. Thanks a lot for your help !
