### ISSUE TITLE
example: align text example

### ISSUE THREAD

**Issue by sondh0127** [ocavue/prosekit#493]
![image](https://github.com/ocavue/prosekit/assets/62163604/71d97fa9-85db-4fce-ad7a-ddceedc811f6)

I try to align current block text, from text color example I modify to use text align as following code.
```ts
export function defineTextColorSpec() {
  return defineMarkSpec({
    name: 'textAlign',
    attrs: {
      textAlign: { default: null },
    },
    parseDOM: [
      {
        style: 'text-align',
        getAttrs: (value) => {
          return { textAlign: value }
        },
      },
    ],
    toDOM: (mark) => {
      return ['div', { style: `text-align: ${mark.attrs.textAlign};` }, 0]
    },
  })
}
```
but there is some unexpected behavior:
- an extra div added, but I actually want to style the <p> instead 
![image](https://github.com/ocavue/prosekit/assets/62163604/4264e285-5480-4ea6-9c47-3161b710e399)
- it's still require to select the current text

Please give me some guide. Thank you @ocavue

**Comment by ocavue** [comment]
Hi, I just implemented text-align in the latest 0.7.0 version. You can check the [document](https://prosekit.dev/extensions/text-align) for detailed usage.
